apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.mariadb.rootPassword }}
  db: {{ .Values.mariadb.database }}
  user: {{ .Values.mariadb.user }}
  user_password: {{ .Values.mariadb.password }}
